TicketProject/Areas/Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicketProject.DataAccess.IReposityory;
using TicketProject.Models;

namespace TicketProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitofwork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            Company company = new Company();
            if (id == null)
            {
                return View(company);
            }
            company = _unitofwork.Company.Get(id.GetValueOrDefault());
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    _unitofwork.Company.Add(company);
                }
                else
                {
                    _unitofwork.Company.Update(company);
                }
                _unitofwork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitofwork.Company.GetAll();
            return Json(new { data = allObj });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitofwork.Company.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = true, message = "Delete Succesfull" });
            }
            _unitofwork.Company.Remove(objFromDb);
            _unitofwork.Save();
            return Json(new { success = true, message = "Delete Succesfull" });
        }
        #endregion
    }
}

TicketProject/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TicketProject.DataAccess.Data;
using TicketProject.DataAccess.IReposityory;
using TicketProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization.Infrastructure;

namespace TicketProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _db.ApplicationUsers.Include(u=>u.Company).ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach(var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
                if(user.Company == null)
                {
                    user.Company = new Company()
                    {
                        Name = " "
                    };
                }
            }
            return Json(new { data = userList });
        }
        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unclocking" });
            }
            if(objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //user is currently locked, we will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Operation Succcesfull" });
        }
        #endregion
    }
}

TicketProject/Areas/Customer/Controllers/TicketController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.OData.Edm;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using TicketProject.Areas.Customer;
using TicketProject.DataAccess.Data;
using TicketProject.DataAccess.IReposityory;
using TicketProject.Models;
using TicketProject.Utility;

namespace TicketProject.Areas.Admin.Controllers
{
    [Area("Customer")]
    public class TicketController : Controller
    {
        public string Username { get; private set; }

        private readonly IUnitOfWork _unitofwork;
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _hostEnvoirement;//resimleri dosyada güncelleme işlemi
        public IEnumerable<SelectListItem> SupportUserList { get; set; }
        public TicketController(IUnitOfWork unitOfWork,ApplicationDbContext db, UserManager<IdentityUser> userManager,IWebHostEnvironment hostEnvironment)
        {
            _userManager = userManager;
            _unitofwork = unitOfWork;
            _hostEnvoirement = hostEnvironment;
            _db = db;
        }
        public async Task<IActionResult> Index(int page = 1, int pageSize = 2)
        {
            var model = new TicketViewModel
            {
                PageNumber = page,
                Tickets = null,
            };
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            //var roles = await _userManager.GetRolesAsync(user);
            await LoadAsync(user);
            if (User.IsInRole(SD.Role_Admin))
            {
                //var allObj = _db.Tickets.Take(2).ToList();
                model.Tickets = await _db.Tickets.Where(u => u.status != RowStatus.Delete).Skip(((page - 1) * pageSize)).Take(pageSize).ToListAsync();
                return View(model);
            }
            if (User.IsInRole(SD.Role_SupportUsers))
            {
                model.Tickets = await _db.Tickets.Where(u => u.status != RowStatus.Delete && u.PersonelTicket != null).Skip(((page - 1) * pageSize)).Take(pageSize).ToListAsync();
                return View(model);
            }
            else if (User.IsInRole(SD.Role_CompanyAgents)){
                ApplicationUser temp = new ApplicationUser();
                temp = _db.ApplicationUsers.Where(u => u.UserName == user.UserName).FirstOrDefault();
                model.Tickets = await _db.Tickets.OrderByDescending(s => s.Id ).Where(u => u.PersonelTicket == temp && u.status != RowStatus.Delete).Skip(((page - 1) * pageSize)).Take(pageSize).ToListAsync();
                return View(model);
            }
            else
            {
                model.Tickets = await _db.Tickets.OrderByDescending(s=> s.Id).Where(u => u.UserEmail == Username && u.status != RowStatus.Delete).Skip(((page - 1) * pageSize)).Take(pageSize).ToListAsync();
                return View(model);
            }
        }
        private async Task LoadAsync(IdentityUser user)
        {
            var userName = await _userManager.GetUserNameAsync(user);
            var phoneNumber = await _userManager.GetPhoneNumberAsync(user);
            Username = userName;
        }
        private IEnumerable<SelectListItem> GetUser()
        {
            var users = _unitofwork.ApplicationUser.GetAll().Select(x=> x.Email).Select(i => new SelectListItem
            {
                Text = i,
                Value = i,
            });
            return new SelectList(users, "Text", "Value");
        }
        public IActionResult UserAdd(int? id)
        {
            var model = new UserRoleViewModel
            {
                UserList = GetUser(),
                ticket = new Ticket(),
            };
            if (id == null)
            {
                return View(model);
            }
            model = new UserRoleViewModel
            {
                UserList = GetUser(),
                ticket = _unitofwork.Ticket.Get(id.GetValueOrDefault()),
            };
            if (model.ticket == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult UserAdd(UserRoleViewModel userRoleViewModel)
        {
            if (ModelState.IsValid)
            {
                Ticket_Management ticket_Management = new Ticket_Management();
                string a = userRoleViewModel.ticket.EmployeeEmail + " ";
                int b = userRoleViewModel.ticket.Id;
                userRoleViewModel.ticket.PersonelTicket = _db.ApplicationUsers.Where(x => x.Email == userRoleViewModel.ticket.EmployeeEmail).FirstOrDefault();
                ticket_Management = _db.Ticket_Managements.Include(a => a.Ticket).Where(u => u.Ticket.Id == userRoleViewModel.ticket.Id).FirstOrDefault();
                ticket_Management.Status = TicketStatus.Seen;
                _unitofwork.Ticket.Update(userRoleViewModel.ticket);
                _unitofwork.Save();
              return RedirectToAction(nameof(Index));
            }
            return View(userRoleViewModel);
        }
        public  IActionResult Upsert(int? id)
        {
            Ticket ticket = new Ticket();
            if(id == null)
            {
                return View(ticket);
            }
            ticket = _unitofwork.Ticket.Get(id.GetValueOrDefault());
            if(ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Ticket ticket)
        {
            Ticket_Management ticket_Management = new Ticket_Management();
            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvoirement.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"images");
                    var extension = Path.GetExtension(files[0].FileName);
                    if (ticket.ImageUrl != null)
                    {
                        //remove old image or edit
                        var imagePath = Path.Combine(webRootPath, ticket.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(filesStreams);
                    }
                    ticket.ImageUrl = @"\images\" + fileName + extension;
                }
                else
                {
                    //update when do not change 
                    if (ticket.Id != 0)
                    {
                        Ticket objFromDb = _unitofwork.Ticket.Get(ticket.Id);
                        ticket.ImageUrl = objFromDb.ImageUrl;
                    }
                }
                if (ticket.Id == 0)
                {
                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
                    }
                    await LoadAsync(user);
                    ticket.CreatingTicket = _db.ApplicationUsers.Where(u => u.Email == Username).FirstOrDefault();
                    ticket.UserEmail = ticket.CreatingTicket.Email;
                    ticket_Management.Ticket = ticket;
                    ticket_Management.Date = Date.Now;
                    ticket_Management.Status = TicketStatus.Sended;
                    _db.Ticket_Managements.Add(ticket_Management);
                    _unitofwork.Ticket.Add(ticket);
                }
                else
                {
                    _unitofwork.Ticket.Update(ticket);
                }
                _unitofwork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var objFromDb = await _db.Tickets.FindAsync(id);
            objFromDb.status = RowStatus.Delete;
            if (objFromDb == null)
            {
                return NotFound();
            }
            _unitofwork.Ticket.Update(objFromDb);
            _unitofwork.Save();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost , ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var objFromDb = await _db.Tickets.FindAsync(id);
            objFromDb.status = RowStatus.Delete;
            if(objFromDb == null)
            {
                return NotFound();
            }
            _unitofwork.Ticket.Update(objFromDb);
            _unitofwork.Save();
            return Redirect(nameof(Index));
        }
        public IActionResult Status(int? id)
        {
            Ticket_Management ticket = new Ticket_Management();
            if (id == null)
            {

TicketProject/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

TicketProject/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

TicketProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicketProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicketProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(TicketProject.Utility.SD.Role_User))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User Menu
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item " asp-area="Customer" asp-controller="Ticket" asp-action="Index">Ticket Manager</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(TicketProject.Utility.SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin Menu
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item " asp-area="Customer" asp-controller="Ticket" asp-action="Index">Ticket Manager</a>
                                    <a class="dropdown-item " asp-area="Admin" asp-controller="Company" asp-action="Index">Company Manager</a>
                                    <a class="dropdown-item " asp-area="Admin" asp-controller="User" asp-action="Index">User Manager</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(TicketProject.Utility.SD.Role_SupportUsers))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    SupportUsers Menu
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item " asp-area="Customer" asp-controller="Ticket" asp-action="Index">Ticket Manager</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(TicketProject.Utility.SD.Role_CompanyAgents))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    CompanyAgent Menu
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item " asp-area="Customer" asp-controller="Ticket" asp-action="Index">Ticket Manager</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-white-50">
            &copy; 2020 - TicketProject
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>